[General]
#Nothing here

[Config Tictoc1]
network = Tictoc1
Tictoc1.toc.limit = 10


[Config Tictoc5]
network = Tictoc5

[Config Tictoc7]
network = Tictoc7
seed-0-mt = 532569  # or any other 32-bit value
# argument to exponential() is the mean; truncnormal() returns values from
# the normal distribution truncated to nonnegative values
Tictoc7.tic.delayTime = exponential(3s)
Tictoc7.toc.delayTime = truncnormal(3s,1s)

[Config Tictoc8]
network = Tictoc8
seed-0-mt = 22

[Config Tictoc9]
network = Tictoc9
seed-0-mt = 22

[Config Tictoc10]
network = Tictoc10

[Config Tictoc13]
network = Tictoc13
